services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    volumes:
      - ./config:/app/config:ro
      - ./assets:/app/assets:ro
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock:ro
