services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      - TZ=${TZ}
    volumes:
      - ./config:/app/config:ro
      - ./assets:/app/assets:ro
      # needed for the docker-containers widget
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock:ro
