# ============================================================================
# Glance Dashboard Configuration - Organized for Interface Flow
# ============================================================================

# Theme Configuration - Enhanced with Rounded Corners
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65
  # Enhanced styling for rounded corners
  border-radius: 12
  widget-border-radius: 8
  card-border-radius: 6

pages:
  # ========================================================================
  # 📊 HOME - Main Dashboard Overview
  # ========================================================================
  - name: Home
    columns:
      # 📅 LEFT: Quick Info & Calendar
      - size: small
        widgets:
          - type: calendar
            title: Calendar
            first-day-of-week: monday

          - type: weather
            title: Weather
            location: ${WEATHER_LOCATION}
            units: ${WEATHER_UNITS}
            hour-format: 12h

          - type: markets
            title: Quick Markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA

          - type: twitch-channels
            title: Live Now
            channels:
              - theprimeagen
              - extraemily
              - ludwig
              - maya

      # 🌐 CENTER: Main Content Feed
      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: group
            title: Tech News & Communities
            widgets:
              - type: hacker-news
                title: Hacker News
              - type: lobsters
                title: Lobsters

          - type: videos
            title: Latest Tech Videos
            collapse-after: 6
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCBJycsmduvYEL83R_U4JriQ # MKBHD
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
              - BrandonButch

          - type: group
            title: Reddit Communities
            widgets:
              - type: reddit
                subreddit: technology
                show-thumbnails: true
                limit: 8
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true
                limit: 8

      # 📰 RIGHT: RSS & Updates
      - size: small
        widgets:
          - type: rss
            title: Tech Blogs
            limit: 12
            collapse-after: 6
            cache: 12h
            feeds:
              - url: https://selfh.st/rss/
                title: selfh.st
                limit: 4
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
                limit: 3
              - url: https://samwho.dev/rss.xml
                title: Sam Who
                limit: 3
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed
                limit: 2

          - type: releases
            title: Software Updates
            cache: 1d
            repositories:
              - glanceapp/glance
              - go-gitea/gitea
              - immich-app/immich
              - syncthing/syncthing

  # ========================================================================
  # 📡 RSS - Dedicated RSS Feed Dashboard
  # ========================================================================
  - name: RSS
    columns:
      # LEFT: RSS Categories
      - size: small
        widgets:
          - type: rss
            title: Tech News
            limit: 8
            collapse-after: 4
            cache: 6h
            feeds:
              - url: https://www.vox.com/rss/index.xml
                title: Vox Tech
                limit: 3
              - url: https://openai.com/news/rss.xml
                title: OpenAI News
                limit: 3
              - url: https://ciechanow.ski/atom.xml
                title: Bartosz Ciechanowski
                limit: 2

          - type: rss
            title: Podcasts
            limit: 6
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://feeds.megaphone.fm/STU4418364045
                title: WVFRM Podcast
                limit: 6

      # CENTER: Embedded RSS Reader
      - size: full
        widgets:
          - type: iframe
            title: Fusion RSS Reader
            url: https://fusion-production-2363.up.railway.app/
            height: 800
            # Alternative if iframe doesn't work:
          # - type: bookmarks
          #   title: RSS Tools
          #   groups:
          #     - title: External RSS Reader
          #       links:
          #         - title: Fusion RSS Reader
          #           url: https://fusion-production-2363.up.railway.app/
          #           icon: si:rss

          - type: rss
            title: All Feeds Combined
            style: horizontal-cards
            limit: 20
            collapse-after: 8
            cache: 6h
            feeds:
              - url: https://selfh.st/rss/
                title: selfh.st
              - url: https://ciechanow.ski/atom.xml
                title: Bartosz Ciechanowski
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
                title: Sam Who
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed
              - url: https://www.vox.com/rss/index.xml
                title: Vox
              - url: https://openai.com/news/rss.xml
                title: OpenAI News

      # RIGHT: RSS Management
      - size: small
        widgets:
          - type: bookmarks
            title: RSS Tools
            groups:
              - title: External Readers
                links:
                  - title: Fusion RSS
                    url: https://fusion-production-2363.up.railway.app/
                    icon: si:rss
                  - title: Feedly
                    url: https://feedly.com/
                    icon: si:feedly
                  - title: Inoreader
                    url: https://www.inoreader.com/
                    icon: si:rss

          - type: rss
            title: Quick Updates
            limit: 6
            collapse-after: 3
            cache: 30m
            feeds:
              - url: https://feeds.bloomberg.com/markets/news.rss
                title: Bloomberg
                limit: 2
              - url: https://moxie.foxbusiness.com/google-publisher/technology.xml
                title: Fox Business Tech
                limit: 2
              - url: https://www.ft.com/technology?format=rss
                title: Financial Times
                limit: 2

  # ========================================================================
  # 🏠 HOMELAB - Infrastructure Dashboard
  # ========================================================================
  - name: Homelab
    columns:
      # LEFT: Quick Access Links
      - size: small
        widgets:
          - type: bookmarks
            title: Cloud Services
            groups:
              - title: Cloudflare
                links:
                  - title: Dashboard
                    url: https://dash.cloudflare.com/
                    icon: si:cloudflare
                  - title: Zero Trust
                    url: https://one.dash.cloudflare.com/
                    icon: si:cloudflare

              - title: Development
                links:
                  - title: GitHub
                    url: https://github.com/
                    icon: si:github
                  - title: Docker Hub
                    url: https://hub.docker.com/
                    icon: si:docker

          - type: dns-stats
            title: Pi-hole DNS
            service: pihole-v6
            url: ${PIHOLE_URL}
            password: ${PIHOLE_PASSWORD}
            token: ${PIHOLE_TOKEN}
            hour-format: 12h

      # CENTER: Service Management
      - size: full
        widgets:
          - type: search
            title: Infrastructure Search
            autofocus: false

          - type: monitor
            title: Core Services Status
            cache: 1m
            sites:
              - title: Portainer
                url: ${PORTAINER_URL}
                icon: si:portainer
              - title: Dokploy
                url: ${DOKPLOY_URL}
                icon: si:docker
              - title: Authentik
                url: ${AUTHENTIK_URL}
                icon: si:authentik
              - title: Uptime Kuma
                url: ${KUMA_URL}
                icon: si:uptimekuma

          - type: monitor
            title: User Services Status
            cache: 2m
            sites:
              - title: Immich Photos
                url: ${IMMICH_URL}
                icon: si:immich
              - title: Nextcloud
                url: ${NEXTCLOUD_URL}
                icon: si:nextcloud
              - title: Vaultwarden
                url: ${VAULTWARDEN_URL}
                icon: si:vaultwarden
              - title: Piped YouTube
                url: ${PIPED_URL}
                icon: si:youtube

          - type: bookmarks
            title: Container Management
            groups:
              - title: Management Interfaces
                links:
                  - title: Portainer
                    url: ${PORTAINER_URL}
                    icon: si:portainer
                  - title: Dokploy
                    url: ${DOKPLOY_URL}
                    icon: si:docker
                  - title: Authentik SSO
                    url: ${AUTHENTIK_URL}
                    icon: si:authentik
                  - title: Uptime Monitor
                    url: ${KUMA_URL}
                    icon: si:uptimekuma

      # RIGHT: System Stats
      - size: small
        widgets:
          - type: server-stats
            title: Main Host
            servers:
              - type: local
                name: Primary Server
                hide-mountpoints-by-default: true

          - type: server-stats
            title: Remote Systems
            servers:
              - type: remote
                name: Raspberry Pi
                url: http://192.168.5.219:61207
                timeout: 15s

          - type: releases
            title: Infrastructure Updates
            cache: 6h
            repositories:
              - portainer/portainer
              - traefik/traefik
              - containrrr/watchtower
              - authelia/authelia

  # ========================================================================
  # 💰 MARKETS - Financial Dashboard
  # ========================================================================
  - name: Markets
    columns:
      # LEFT: Market Overview
      - size: small
        widgets:
          - type: markets
            title: Major Indices
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: QQQ
                name: NASDAQ 100
              - symbol: DX-Y.NYB
                name: Dollar Index

          - type: markets
            title: Crypto Markets
            markets:
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: ETH-USD
                name: Ethereum
              - symbol: SOL-USD
                name: Solana

          - type: rss
            title: Market News
            limit: 8
            collapse-after: 4
            cache: 30m
            feeds:
              - url: https://feeds.bloomberg.com/markets/news.rss
                title: Bloomberg Markets
                limit: 4
              - url: https://feeds.a.dj.com/rss/RSSMarketsMain.xml
                title: WSJ Markets
                limit: 4

      # CENTER: Detailed Markets & Content
      - size: full
        widgets:
          - type: markets
            title: Stock Watchlist
            sort-by: absolute-change
            markets:
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft
              - symbol: GOOGL
                name: Google
              - symbol: AMD
                name: AMD
              - symbol: TSLA
                name: Tesla
              - symbol: META
                name: Meta
              - symbol: AMZN
                name: Amazon
              - symbol: RDDT
                name: Reddit
              - symbol: INTC
                name: Intel

          - type: videos
            title: Financial Content
            style: grid-cards
            collapse-after-rows: 2
            channels:
              - UCvSXMi2LebwJEM1s4bz5IBA # New Money
              - UCV6KDgJskWaEckne5aPA0aQ # Graham Stephan
              - UCAzhpt9DmG6PnHXjmJTvRGQ # Federal Reserve

          - type: group
            title: Financial Communities
            widgets:
              - type: reddit
                subreddit: investing
                show-thumbnails: true
                limit: 6
              - type: reddit
                subreddit: wallstreetbets
                show-thumbnails: true
                limit: 6

      # RIGHT: Financial News & Analysis
      - size: small
        widgets:
          - type: rss
            title: Financial Analysis
            limit: 15
            collapse-after: 8
            cache: 1h
            feeds:
              - url: https://www.ft.com/technology?format=rss
                title: FT Technology
                limit: 5
              - url: https://moxie.foxbusiness.com/google-publisher/markets.xml
                title: Fox Business
                limit: 5
              - url: https://moxie.foxbusiness.com/google-publisher/technology.xml
                title: Fox Tech
                limit: 5

          - type: bookmarks
            title: Trading Tools
            groups:
              - title: Platforms
                links:
                  - title: Yahoo Finance
                    url: https://finance.yahoo.com/
                    icon: si:yahoo
                  - title: TradingView
                    url: https://www.tradingview.com/
                    icon: si:tradingview
                  - title: MarketWatch
                    url: https://www.marketwatch.com/
                    icon: si:marketwatch

  # ========================================================================
  # 🚀 STARTPAGE - Clean Minimal Interface
  # ========================================================================
  - name: Startpage
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: search
            title: Search
            autofocus: true

          - type: monitor
            title: Essential Services
            cache: 2m
            style: cards
            sites:
              - title: Immich Photos
                url: ${IMMICH_URL}
                icon: si:immich
              - title: Vaultwarden
                url: ${VAULTWARDEN_URL}
                icon: si:vaultwarden
              - title: Nextcloud
                url: ${NEXTCLOUD_URL}
                icon: si:nextcloud
              - title: Jellyfin
                url: ${JELLYFIN_URL:-https://yourdomain.com/}
                icon: si:jellyfin
              - title: Gitea
                url: ${GITEA_URL:-https://yourdomain.com/}
                icon: si:gitea
              - title: qBittorrent
                url: ${QBITTORRENT_URL:-https://yourdomain.com/}
                icon: si:qbittorrent

          - type: bookmarks
            title: Quick Links
            groups:
              - title: Daily
                links:
                  - title: Gmail
                    url: https://mail.google.com/mail/u/0/
                    icon: si:gmail
                  - title: GitHub
                    url: https://github.com/
                    icon: si:github
                  - title: Amazon
                    url: https://www.amazon.com/
                    icon: si:amazon

              - title: Media
                links:
                  - title: YouTube
                    url: https://www.youtube.com/
                    icon: si:youtube
                  - title: Prime Video
                    url: https://www.primevideo.com/
                    icon: si:amazonprime
                  - title: Disney+
                    url: https://www.disneyplus.com/
                    icon: si:disneyplus

              - title: Social
                links:
                  - title: Reddit
                    url: https://www.reddit.com/
                    icon: si:reddit
                  - title: Twitter/X
                    url: https://x.com/
                    icon: si:x
                  - title: Instagram
                    url: https://www.instagram.com/
                    icon: si:instagram
