title: Milo — Glance

theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  # ===== Home (default layout) =====
  - name: Home
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: monday

          - type: rss
            limit: 20
            collapse-after: 3
            cache: 12h
            feeds:
              - url: https://selfh.st/rss/
                title: selfh.st
                limit: 4
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadeed
              - url: https://www.vox.com/rss/index.xml
                title: Vox
              - url: https://feeds.megaphone.fm/STU4418364045
                title: WVFRM Podcast
          - type: twitch-channels
            channels:
              - theprimeagen
              - extraemily
              - ludwig
              - ninadaddyisback
              - maya
              - qtcinderella
              - arky

      - size: full
        widgets:
          - type: group
            widgets:
              - type: hacker-news
              - type: lobsters

          - type: videos
            channels:
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCsBjURrPoezykLs9EqgamOA # Fireship
              - UCBJycsmduvYEL83R_U4JriQ # MKBHD
              - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
              - BrandonButch

          - type: group
            widgets:
              - type: reddit
                subreddit: technology
                show-thumbnails: true
              - type: reddit
                subreddit: selfhosted
                show-thumbnails: true

      - size: small
        widgets:
          - type: weather
            location: ${WEATHER_LOCATION}
            units: ${WEATHER_UNITS}
            hour-format: 12h

          - type: releases
            cache: 1d
            repositories:
              - glanceapp/glance
              - go-gitea/gitea
              - immich-app/immich
              - syncthing/syncthing

          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft

  # ===== Homelab =====
  - name: Homelab
    columns:
      # LEFT: Bookmarks (moved where Services used to be)
      - size: small
        widgets:
          - type: bookmarks
            groups:
              - title: DevOps & Sysadmin
                links:
                  - title: Cloudflare Dashboard
                    url: https://dash.cloudflare.com/
                    icon: si:cloudflare
                  - title: Cloudflare Zero Trust
                    url: https://one.dash.cloudflare.com/
                    icon: si:cloudflare
                  - title: Cloudflare Tunnels
                    url: https://one.dash.cloudflare.com/
                    icon: si:cloudflare
                  - title: Portainer
                    url: ${PORTAINER_URL}
                    icon: si:portainer
                  - title: Dokploy
                    url: ${DOKPLOY_URL}
                    icon: si:docker
                  - title: Uptime Kuma
                    url: ${KUMA_URL}
                    icon: si:uptimekuma
                  - title: Authentik
                    url: ${AUTHENTIK_URL}
                    icon: si:authentik
                  - title: GitHub
                    url: https://github.com/
                    icon: si:github
                  - title: Docker Hub
                    url: https://hub.docker.com/
                    icon: si:docker

      # MIDDLE: Search (on top) + Services (centered)
      - size: full
        widgets:
          - type: search
            autofocus: true
          - type: monitor
            title: Services
            cache: 1m
            sites:
              - title: Portainer
                url: ${PORTAINER_URL}
                icon: si:portainer
              - title: Dokploy
                url: ${DOKPLOY_URL}
                icon: si:docker
              - title: Authentik
                url: ${AUTHENTIK_URL}
                icon: si:authentik
              - title: Uptime Kuma
                url: ${KUMA_URL}
                icon: si:uptimekuma
              - title: Piped
                url: ${PIPED_URL}
                icon: si:youtube
              - title: Immich
                url: ${IMMICH_URL}
                icon: si:immich
              - title: Nextcloud
                url: ${NEXTCLOUD_URL}
                icon: si:nextcloud
              - title: Vaultwarden
                url: ${VAULTWARDEN_URL}
                icon: si:vaultwarden

      # RIGHT: Lab stats (DNS + server stats)
      - size: small
        widgets:
          - type: dns-stats
            title: DNS (Pi-hole)
            service: pihole-v6        # use 'pihole' + token if v5
            url: ${PIHOLE_URL}
            password: ${PIHOLE_PASSWORD}
            token: ${PIHOLE_TOKEN}
            hour-format: 12h

          - type: server-stats
            servers:
              - type: local
                name: Host
                hide-mountpoints-by-default: true
              - type: remote
                name: Raspberry Pi
                url: http://192.168.5.219:61207
                timeout: 15s

  # ===== Markets (preset) =====
  - name: Markets
    columns:
      - size: small
        widgets:
          - type: markets
            title: Indices
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: DX-Y.NYB
                name: Dollar Index

          - type: markets
            title: Crypto
            markets:
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: ETH-USD
                name: Ethereum

          - type: markets
            title: Stocks
            sort-by: absolute-change
            markets:
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft
              - symbol: GOOGL
                name: Google
              - symbol: AMD
                name: AMD
              - symbol: RDDT
                name: Reddit
              - symbol: AMZN
                name: Amazon
              - symbol: TSLA
                name: Tesla
              - symbol: INTC
                name: Intel
              - symbol: META
                name: Meta

      - size: full
        widgets:
          - type: rss
            title: News
            style: horizontal-cards
            feeds:
              - url: https://feeds.bloomberg.com/markets/news.rss
                title: Bloomberg
              - url: https://moxie.foxbusiness.com/google-publisher/markets.xml
                title: Fox Business
              - url: https://moxie.foxbusiness.com/google-publisher/technology.xml
                title: Fox Business

          - type: group
            widgets:
              - type: reddit
                show-thumbnails: true
                subreddit: technology
              - type: reddit
                show-thumbnails: true
                subreddit: wallstreetbets

          - type: videos
            style: grid-cards
            collapse-after-rows: 3
            channels:
              - UCvSXMi2LebwJEM1s4bz5IBA # New Money
              - UCV6KDgJskWaEckne5aPA0aQ # Graham Stephan
              - UCAzhpt9DmG6PnHXjmJTvRGQ # Federal Reserve

      - size: small
        widgets:
          - type: rss
            title: News
            limit: 30
            collapse-after: 13
            feeds:
              - url: https://www.ft.com/technology?format=rss
                title: Financial Times
              - url: https://feeds.a.dj.com/rss/RSSMarketsMain.xml
                title: Wall Street Journal

  # ===== Startpage (minimal) =====
  - name: Startpage
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Jellyfin
                url: https://yourdomain.com/
                icon: si:jellyfin
              - title: Gitea
                url: https://yourdomain.com/
                icon: si:gitea
              - title: qBittorrent
                url: https://yourdomain.com/
                icon: si:qbittorrent
              - title: Immich
                url: https://yourdomain.com/
                icon: si:immich
              - title: AdGuard Home
                url: https://yourdomain.com/
                icon: si:adguard
              - title: Vaultwarden
                url: https://yourdomain.com/
                icon: si:vaultwarden

          - type: bookmarks
            groups:
              - title: General
                links:
                  - title: Gmail
                    url: https://mail.google.com/mail/u/0/
                  - title: Amazon
                    url: https://www.amazon.com/
                  - title: Github
                    url: https://github.com/
              - title: Entertainment
                links:
                  - title: YouTube
                    url: https://www.youtube.com/
                  - title: Prime Video
                    url: https://www.primevideo.com/
                  - title: Disney+
                    url: https://www.disneyplus.com/
              - title: Social
                links:
                  - title: Reddit
                    url: https://www.reddit.com/
                  - title: Twitter
                    url: https://twitter.com/
                  - title: Instagram
                    url: https://www.instagram.com/
