name: Home
columns:
  - size: small
    widgets:
      - type: search
        autofocus: true
      - type: weather
        location: ${WEATHER_LOCATION}
        units: ${WEATHER_UNITS}
        hour-format: 12h
  - size: full
    widgets:
      - type: hacker-news
        limit: 20
        collapse-after: 5
  - size: small
    widgets:
      - type: reddit
        subreddit: selfhosted
        show-thumbnails: true